- become: true
  sysctl:
    name: net.core.rmem_max
    value: "600000000"
    state: present
- become: true
  sysctl:
    name: net.core.wmem_max
    value: "600000000"
    state: present
- become: true
  shell: sudo sysctl -w net.core.rmem_max=600000000 && sudo sysctl -w net.core.wmem_max=600000000
