- become: true
  shell: |
    echo '[Unit]
    Description=Quilibrium node
    [Service]
    Type=simple
    Restart=always
    RestartSec=5s
    WorkingDirectory={{ node_path }}/ceremonyclient/node
    Environment="GOMAXPROCS={{ go_max_procs}}"
    Environment="GOEXPERIMENT=arenas"
    ExecStart={{ node_path }}/ceremonyclient/node/node
    User={{ ansible_user }}
    [Install]
    WantedBy=multi-user.target' > /lib/systemd/system/quilibrium.service
    systemctl daemon-reload
    systemctl enable quilibrium.service
