- name: Remove dead screens
  shell: screen -wipe
  ignore_errors: true

- name: Find screen process ID
  shell: screen -S quilibrium -Q echo '$PID'
  register: quilibrium_pid
  ignore_errors: true

- block:
    - name: "End play when node PID is not found"
      debug:
        msg: "Node is not running"
    - meta: end_play
  when: quilibrium_pid.failed == true

- name: Kill Quilibrium node process
  when: quilibrium_pid.stdout.strip() != ""
  shell: kill -9 {{ quilibrium_pid.stdout.strip() }}
  register: quilibrium_kill

- name: Report error if node failed to stop
  when: quilibrium_kill.rc is defined and quilibrium_kill.rc != 0
  debug:
    msg: "Failed to stop Quilibrium node. Check logs for details."

- name: Check if node stopped successfully
  when: quilibrium_kill.rc is defined and  quilibrium_kill.rc == 0
  debug:
    msg: "Quilibrium node stopped successfully."
