- name: Find Quilibrium node process ID
  shell: screen -ls | grep quilibrium | awk '{print $1}'
  register: quilibrium_pid

- name: Report error if node failed to stop
  when: quilibrium_pid.stdout.strip() == ""
  fail:
    msg: "Node is not running"

- name: Kill Quilibrium node process
  when: quilibrium_pid.stdout.strip() != ""
  shell: screen -S {{ quilibrium_pid.stdout.strip() }} -X kill
  register: quilibrium_kill

- name: Report error if node failed to stop
  when: quilibrium_kill.rc != 0
  fail:
    msg: "Failed to stop Quilibrium node. Check logs for details."

- name: Check if node stopped successfully
  when: quilibrium_kill.rc == 0
  debug:
    msg: "Quilibrium node stopped successfully."
