- name: Install Watchdog
  hosts: "{{ target }}"
  vars:
    watchdog: "{{ node_path }}/watchdog"

  tasks:
    - name: Update and upgrade apt packages
      include_role:
        name: roles/system/update-os
    - name: Install required packages
      become: true
      apt:
        name: 
          - python3
          - python3-pip
          - python3-virtualenv
        state: present

    - name: Create watchdog directory
      file:
        path: "{{ watchdog }}"
        state: directory

    - name: Remove previous script
      file:
        path: "{{ watchdog }}/watchdog.py"
        state: absent

    - name: Remove previous requirements
      file:
        path: "{{ watchdog }}/requirements.txt"
        state: absent

    - name: Install watchdog
      copy:
        src: "../../scripts/watchdog/watchdog.py"
        dest: "{{ watchdog }}/watchdog.py"
        owner: "{{ ansible_user }}"

    - name: Install requirements
      copy:
        src: "../../scripts/watchdog/requirements.txt"
        dest: "{{ watchdog }}/requirements.txt"
        owner: "{{ ansible_user }}"

   # - name: Create virtual env
   #   shell: |
   #     cd {{ watchdog }}
        #python3 -m venv env

    - name: Create python virtual env and install modules
      pip:
        requirements: "{{ watchdog }}/requirements.txt"
        virtualenv: "{{ watchdog }}/myenv"
        virtualenv_command: virtualenv

    - name: Set auto_restart parameter
      ini_file:
        path: "{{ watchdog }}/.env"
        option: AUTO_RESTART
        section: node
        value: "{{ auto_restart }}"
        state: present
      when: auto_restart is defined

    - name: Set publish_level parameter
      ini_file:
        path: "{{ watchdog }}/.env"
        option: PUBLISH_LEVEL
        section: notification
        value: "{{ publish_level }}"
        state: present
      when: publish_level is defined

    - name: Set telegram_id parameter
      ini_file:
        path: "{{ watchdog }}/.env"
        option: TELEGRAM_USER_ID
        section: notification
        value: "{{ telegram_id }}"
        state: present
      when: telegram_id is defined

    - name: Set discord_webhook parameter
      ini_file:
        path: "{{ watchdog }}/.env"
        option: DISCORD_WEBHOOK_URL
        section: notification
        value: "{{ discord_webhook }}"
        state: present
      when: discord_webhook is defined

    - name: Install watchdog service
      become: true
      shell: |
        echo '[Unit]
        Description=Quilibrium watchdog service
        [Service]
        Type=simple
        RestartSec=3600s
        WorkingDirectory={{ watchdog }}
        Environment=GOEXPERIMENT=arenas
        ExecStart={{ watchdog }}/myenv/bin/python3 watchdog.py
        User={{ ansible_user }}
        [Install]
        WantedBy=multi-user.target' > /lib/systemd/system/quilibrium_watchdog.service

    - name: Enable watchdog service
      become: true
      shell: |
        systemctl daemon-reload
        systemctl enable quilibrium_watchdog.service
        systemctl restart quilibrium_watchdog.service

    
