- replace:
    path: "{{ node_path }}/ceremonyclient/node/.config/config.yml"
    regexp: 'statsMultiaddr: ""'
    replace: 'statsMultiaddr: "/dns/stats.quilibrium.com/tcp/443"'

- replace:
    path: "{{ node_path }}/ceremonyclient/node/.config/config.yml"
    regexp: 'listenGrpcMultiaddr: ""'
    replace: "listenGrpcMultiaddr: /ip4/127.0.0.1/tcp/8337"

- replace:
    path: "{{ node_path }}/ceremonyclient/node/.config/config.yml"
    regexp: 'listenRESTMultiaddr: ""'
    replace: "listenRESTMultiaddr: /ip4/127.0.0.1/tcp/8338"
