rigs:
  vars:
    ansible_user: miner
    ansible_password: '{{ miner }}'
  hosts:
    worker01:
      ansible_host: 10.211.0.21
    worker02:
      ansible_host: 10.211.0.22
    worker03:
      ansible_host: 10.211.0.23
    worker04:
      ansible_host: 10.211.0.24
    worker05:
      ansible_host: 10.211.0.25
    worker06:
      ansible_host: 10.211.0.26

quilibrium:
  vars:
    ansible_user: fpa
    ansible_password: '{{ fpa }}'
  hosts:
    quilibrium01:
      ansible_host: 10.50.0.101
    quilibrium02:
      ansible_host: 10.50.0.102
    quilibrium03:
      ansible_host: 10.50.0.103
    quilibrium04:
      ansible_host: 10.50.0.104
    quilibrium05:
      ansible_host: 10.50.0.105
    quilibrium06:
      ansible_host: 10.50.0.106
    quilibrium07:
      ansible_host: 10.50.1.107
    quilibrium08:
      ansible_host: 10.50.1.108
    quilibrium09:
      ansible_host: 10.50.1.109
    quilibrium10:
      ansible_host: 10.50.1.110
    quilibrium11:
      ansible_host: 10.50.1.111
    quilibrium12:
      ansible_host: 10.50.1.112

others:
  vars:
    ansible_user: fpa
    ansible_password: '{{ fpa }}'
  hosts:
    worker-mac-01:
      ansible_host: 10.211.0.13
    worker-dell-02:
      ansible_host: 10.211.0.10
    worker-huawei-01:
      ansible_host: 10.211.0.11
    mac-kandy:
      ansible_host: 10.58.1.212
      ansible_user: kandy
      ansible_password: '{{ kandy }}'