---
- name: Get Quilibrium reward
  hosts: "{{ target }}"

  tasks:
    - name: Get node information from quilibrium node
      uri:
        url: "{{ quilibrium_api_url }}/quilibrium.node.node.pb.NodeService/GetNodeInfo"
        method: POST
      register: node_info
    - name: Check if request was successful
      when: node_info.status != 200
      fail:
        msg: "Failed to get node information: {{ node_info.msg }}"

    - name: Get rewards from quilibrium website
      command: "python3 ../../scripts/rewards.py {{ node_info.json.peerId }}"
      delegate_to: 127.0.0.1
      register: rewards

    - name: Creates directory
      file:
        path: ../../rewards
        state: directory
      delegate_to: localhost

    - name: Save output to file
      copy:
        content: |-
          Host;Peer ID;Existing (Jan-May 13);Pre-1.4.18;Post-1.4.18;Total;Disqualified;Criteria
          {% for host in ansible_play_hosts_all %}
          {{ host }};{{ hostvars[host]['rewards']['stdout'] if 'rewards' in hostvars[host] else ';;;;;;' }}
          {% endfor %}
        dest: ../../rewards/rewards.csv
      delegate_to: localhost
      run_once: true
