- name: Install Quilibrium node
  hosts: "{{ target }}"

  tasks:
    - name: Check if node already installed
      stat:
        path: "{{ node_path }}"
      register: node_check
    - name: Stop playbook if node exists
      fail:
        msg: "Directory '{{ node_path }}' already exists. Playbook aborted."
      when: node_check.stat.exists

    - name: Update and upgrade apt packages
      include_role:
        name: roles/system/update-os
    - name: Install required packages
      include_role:
        name: roles/system/install-dependencies
    - name: Update sysctl
      include_role:
        name: roles/system/sysctl

    - name: Install go
      include_role:
        name: roles/system/install-go

    - name: Install Quilibrium node
      shell: |
        export GOROOT=/usr/local/go
        export GOPATH=$HOME/go
        export PATH=$GOPATH/bin:$GOROOT/bin:$PATH
        source {{ ansible_env.HOME }}/.bashrc
        rm -rf {{ node_path }}
        mkdir -p {{ node_path }}
        cd {{ node_path }}
        git clone https://source.quilibrium.com/quilibrium/ceremonyclient.git
        cd ceremonyclient
        git checkout release
        cd node
        ln -s ./node-1.4.18-linux-amd64 ./node
      args:
        executable: /bin/bash

    - name: Check if node is installed
      stat:
        path: "{{ node_path }}"
      register: node_check
    - name: Fail if node installation fails
      fail:
        msg: "Error installing Quilibrium node."
      when: not node_check.stat.exists
    - name: Success message
      debug:
        msg: "Quilibrium node has been successfully installed."
      when: node_check.stat.exists

    - name: Create Quilibrium service
      include_role:
        name: roles/node/create_service

    - name: Start Quilibrium node
      include_role:
        name: roles/node/start_node
    - name: Stop Quilibrium node
      include_role:
        name: roles/node/stop_node

    - name: Update node configuration
      include_role:
        name: roles/node/update_node_configuration
