- name: Restore node configuration
  hosts: "{{ target }}"

  tasks:
    - name: Restore config.yml
      copy:
        src: ../../backup/{{ inventory_hostname }}/config.yml
        dest: "{{ node_path }}/ceremonyclient/node/.config/config.yml"

    - name: Restore keys.yml
      copy:
        src: ../../backup/{{ inventory_hostname }}/keys.yml
        dest: "{{ node_path }}/ceremonyclient/node/.config/keys.yml"
