- name: Start Quilibrium node
  hosts: "{{ target }}"

  tasks:
    - name: start node
      include_role:
        name: roles/node/start_node
    - name: start watchdog
      include_role:
        name: roles/watchdog/start_watchdog
