- name: Stop Quilibrium node
  hosts: "{{ target }}"

  tasks:
    - block:
      - name: stop watchdog
        include_role:
          name: roles/watchdog/stop_watchdog
      ignore_errors: true

    - name: stop node
      include_role:
        name: roles/node/stop_node
