- name: Stop Quilibrium node
  hosts: "{{ target }}"

  tasks:
    - name: stop node
      include_role:
        name: roles/node/stop_node
    - name: stop watchdog
      include_role:
        name: roles/watchdog/stop_watchdog
