- name: Upgrade Quilibrium node
  hosts: "{{ target }}"

  tasks:
    - name: Check if node is installed
      stat:
        path: "{{ node_path }}/ceremonyclient/node/.config"
      register: node_check
    - name: Stop playbook if node not exists
      fail:
        msg: "Directory '{{ node_path }}/ceremonyclient/node/.config' not exists. Playbook aborted."
      when: not(node_check.stat.exists)

    - block:
      - name: Stop Quilibrium node
        include_role:
          name: roles/node/stop_node
      ignore_errors: true

    - name: Update Quilibrium node
      shell: |
        export GOROOT=/usr/local/go
        export GOPATH=$HOME/go
        export PATH=$GOPATH/bin:$GOROOT/bin:$PATH
        source {{ ansible_env.HOME }}/.bashrc
        cd {{ node_path }}/ceremonyclient
        git remote set-url origin https://source.quilibrium.com/quilibrium/ceremonyclient.git
        git pull
        git checkout release-cdn
        cd node
        rm -f ./node
        file=$(find . -type f -name "*amd64*" -executable | head -n 1)
        if [ -n "$file" ]; then
            ln -s $file ./node
        else
            return 1
        fi
      args:
        executable: /bin/bash

    - block:
      - name: Start Quilibrium node
        include_role:
          name: roles/node/start_node
      ignore_errors: true
