- name: Upgrade Quilibrium node
  hosts: "{{ target }}"

  tasks:
    - become: true
      apt:
        name:
          - curl
        state: present

    - name: Check if node is installed
      stat:
        path: "{{ node_path }}/ceremonyclient/node/.config"
      register: node_check
    - name: Stop playbook if node not exists
      fail:
        msg: "Directory '{{ node_path }}/ceremonyclient/node/.config' not exists. Playbook aborted."
      when: not(node_check.stat.exists)

    - block:
      - name: Stop watchdog
        include_role:
          name: roles/watchdog/stop_watchdog
      ignore_errors: true
    - block:
      - name: Stop Quilibrium node
        include_role:
          name: roles/node/stop_node
      ignore_errors: true

    - name: Update Quilibrium node
      shell: |
        export GOROOT=/usr/local/go
        export GOPATH=$HOME/go
        export PATH=$GOPATH/bin:$GOROOT/bin:$PATH
        source {{ ansible_env.HOME }}/.bashrc
        cd {{ node_path }}/ceremonyclient
        git remote set-url origin https://github.com/QuilibriumNetwork/ceremonyclient.git
        git pull
        git checkout release
        cd node

        \rm -f ./node*
        files=$(curl https://releases.quilibrium.com/release)
        for file in $files; do
            if ! test -f "./$file"; then
                curl "https://releases.quilibrium.com/$file" > "$file"
            fi
        done

        if [[ "$OSTYPE" == "linux-gnu"* ]]; then
          if [[ $(uname -m) == "aarch64"* ]]; then
            file=$(find . -type f -name "*linux*arm64" | head -n 1)
          else
            file=$(find . -type f -name "*linux*amd64" | head -n 1)
          fi
        elif [[ "$OSTYPE" == "darwin"* ]]; then
          file=$(find . -type f -name "*darwin*arm64" | head -n 1)
        else
          return 1
        fi

        if [ -n "$file" ]; then
            chmod +x $file
            ln -s $file ./node
        else
            return 1
        fi
      args:
        executable: /bin/bash

    - block:
      - name: Start Quilibrium node
        include_role:
          name: roles/node/start_node
      ignore_errors: true
    - block:
      - name: Start watchdog
        include_role:
          name: roles/node/start_watchdog
      ignore_errors: true

