---
- name: Get Quilibrium reward
  hosts: "{{ target }}"

  tasks:
    - name: Include variables
      include_vars: ../defaults/vars.yml

    - name: Get node information from quilibrium node
      uri:
        url: "{{ quilibrium_api_url }}/quilibrium.node.node.pb.NodeService/GetNodeInfo"
        method: POST
      register: node_info
    - name: Check if request was successful
      when: node_info.status != 200
      fail:
        msg: "Failed to get node information: {{ node_info.msg }}"

    - name: Get rewards from quilibrium website
      command: "python3 ../scripts/rewards.py {{ node_info.json.peerId }}"
      delegate_to: 127.0.0.1
      register: rewards

    - name: Display script output
      debug:
        msg: "{{ rewards.stdout_lines[-1:] }}"