- name: Install Quilibrium node
  hosts: "{{ target }}"

  tasks:
    - name: Include variables
      include_vars: ../defaults/vars.yml

    - name: Check if node already installed
      stat:
        path: "{{ node_path }}"
      register: node_check
    - name: Stop playbook if node exists (corrected)
      fail:
        msg: "Directory '{{ node_path }}' already exists. Playbook aborted."
      when: node_check.stat.exists

    - name: Update and upgrade apt packages
      become: true
      apt:
        upgrade: yes
        update_cache: yes

    - name: Install required packages
      become: true
      apt:
        name:
          - git
          - screen
          - wget
          - btop
          - cron
          - zip
          - unzip
          - vim
          - nano
          - ip-utils

    - name: Update sysctl (rmem_max)
      become: true
      sysctl:
        name: net.core.rmem_max
        value: "7500000"
        state: present
    - name: Update sysctl (wmem_max)
      become: true
      sysctl:
        name: net.core.wmem_max
        value: "7500000"
        state: present
    - name: Update sysctl (dynamic)
      become: true
      shell: sudo sysctl -w net.core.rmem_max=7500000 && sudo sysctl -w net.core.wmem_max=7500000

    - name: Install go
      become: true
      shell: |
        wget https://go.dev/dl/go1.20.14.linux-amd64.tar.gz
        sudo tar -xvf go1.20.14.linux-amd64.tar.gz 
        sudo rm -rf /usr/local/go
        sudo mv go /usr/local
        sudo rm go1.20.14.linux-amd64.tar.gz

    - name: Add go to user path
      shell: |
        echo "" >> ~/.bashrc
        echo "GOROOT=/usr/local/go" >> ~/.bashrc
        echo "GOPATH=\$HOME/go" >> ~/.bashrc
        echo "PATH=\$GOPATH/bin:\$GOROOT/bin:\$PATH" >> ~/.bashrc

    - name: Install Quilibrium node
      shell: |
        export GOROOT=/usr/local/go
        export GOPATH=$HOME/go
        export PATH=$GOPATH/bin:$GOROOT/bin:$PATH
        source {{ ansible_env.HOME }}/.bashrc
        rm -rf {{ node_path }}
        mkdir -p {{ node_path }}
        cd {{ node_path }}
        git clone https://github.com/QuilibriumNetwork/ceremonyclient.git
        cd ceremonyclient/node
        GOEXPERIMENT=arenas /usr/local/go/bin/go build .
      args:
        executable: /bin/bash

    - name: Launch Quilibrium node at reboot
      shell: (crontab -u {{ ansible_user }} -l; echo "@reboot sleep 30 && cd {{ node_path }}/ceremonyclient/node && screen -dmS quilibrium ./node") | crontab -u {{ ansible_user }} -

    - name: Check if node is installed
      stat:
        path: "{{ node_path }}"
      register: node_check
    - name: Fail if node installation fails
      fail:
        msg: "Error installing Quilibrium node."
      when: not node_check.stat.exists
    - name: Success message
      debug:
        msg: "Quilibrium node has been successfully installed."
      when: node_check.stat.exists
